// <auto-generated />
using System;
using BarberSystem.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberSystem.Infrastructure.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    [Migration("20251218162048_UpdateDatabase")]
    partial class UpdateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarberSystem.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentitySystemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdentitySystemId")
                        .IsUnique();

                    b.ToTable("customers");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.IdentitySystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileType")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("identitysSystem");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.Scheduling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TotalServiceTime")
                        .HasColumnType("time");

                    b.Property<double>("TotalValue")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("schedulings");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.SchedulingService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("DurationAtMoment")
                        .HasColumnType("time");

                    b.Property<decimal>("PriceAtMoment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SchedulingId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceProvidedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchedulingId");

                    b.HasIndex("ServiceProvidedId");

                    b.ToTable("schedulingServices");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.ServiceProvided", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("ServiceTime")
                        .HasColumnType("time");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("servicesProvideds");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DismissalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("HiringDate")
                        .HasColumnType("date");

                    b.Property<int>("IdentitySystemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdentitySystemId")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("workSchedules");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.Customer", b =>
                {
                    b.HasOne("BarberSystem.Domain.Entities.IdentitySystem", "IdentitySystem")
                        .WithOne("Customer")
                        .HasForeignKey("BarberSystem.Domain.Entities.Customer", "IdentitySystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BarberSystem.Domain.ValueObjects.Cpf", "CPF", b1 =>
                        {
                            b1.Property<int>("CustomerId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nchar(11)")
                                .HasColumnName("CPF")
                                .IsFixedLength();

                            b1.HasKey("CustomerId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("IdentitySystem");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.IdentitySystem", b =>
                {
                    b.OwnsOne("BarberSystem.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("IdentitySystemId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Email");

                            b1.HasKey("IdentitySystemId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("identitysSystem");

                            b1.WithOwner()
                                .HasForeignKey("IdentitySystemId");
                        });

                    b.OwnsOne("BarberSystem.Domain.ValueObjects.Password", "Password", b1 =>
                        {
                            b1.Property<int>("IdentitySystemId")
                                .HasColumnType("int");

                            b1.Property<byte[]>("HashPassword")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Hash");

                            b1.Property<byte[]>("SaltPassword")
                                .IsRequired()
                                .HasColumnType("varbinary(max)")
                                .HasColumnName("Salt");

                            b1.HasKey("IdentitySystemId");

                            b1.ToTable("identitysSystem");

                            b1.WithOwner()
                                .HasForeignKey("IdentitySystemId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.Scheduling", b =>
                {
                    b.HasOne("BarberSystem.Domain.Entities.Customer", "Customer")
                        .WithMany("Schedulings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarberSystem.Domain.Entities.User", "User")
                        .WithMany("Schedulings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.SchedulingService", b =>
                {
                    b.HasOne("BarberSystem.Domain.Entities.Scheduling", null)
                        .WithMany("Services")
                        .HasForeignKey("SchedulingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarberSystem.Domain.Entities.ServiceProvided", null)
                        .WithMany("Services")
                        .HasForeignKey("ServiceProvidedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("BarberSystem.Domain.Entities.IdentitySystem", "IdentitySystem")
                        .WithOne("User")
                        .HasForeignKey("BarberSystem.Domain.Entities.User", "IdentitySystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BarberSystem.Domain.ValueObjects.Cpf", "CPF", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nchar(11)")
                                .HasColumnName("CPF")
                                .IsFixedLength();

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("IdentitySystem");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("BarberSystem.Domain.Entities.User", "User")
                        .WithOne("WorkSchedule")
                        .HasForeignKey("BarberSystem.Domain.Entities.WorkSchedule", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Schedulings");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.IdentitySystem", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.Scheduling", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.ServiceProvided", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("BarberSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("Schedulings");

                    b.Navigation("WorkSchedule")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
